version: '1.0.0-{build}'

branches:
 only:
   - master

environment:
 auth_token:
   secure: sKEakSgMX5/XJ2rS2H6dGsTFztE6N7uwSEGSs2b5r2/dMfl9iWs1vKkjkTkeGcG5
 matrix:
   - prepare_mode: YES
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
     arch_name: x86
     build_tool: msvc2019
     build_suite: msvc2019_32
     qt: msvc2019
   - prepare_mode: NO
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
     arch_name: x86
     build_tool: msvc2019
     build_suite: msvc2019_32
     qt: msvc2019
   - prepare_mode: NO
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
     arch_name: x64
     build_tool: msvc2019
     build_suite: msvc2019_64
     qt: msvc2019_64

clone_folder: c:\dev\quentier-dependencies-windows

init:
  - if %build_tool%==msvc2019 set PATH=C:\Qt\5.15\%qt%\bin;%PATH%
  - set ORIGPATH=%PATH%
  - if %build_suite%==msvc2019_64 set tool=VS2019_x64
  - if %build_suite%==msvc2019_32 set tool=VS2019_x32
  - if %build_suite%==msvc2019_64 call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if %build_suite%==msvc2019_32 call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x86
  - set MAKEFILES="NMake Makefiles"
  - set PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin";%PATH%
  - if %build_suite%==msvc2019_32 set SCRIPTSDIR=c:\dev\quentier-dependencies-windows\scripts\msvc2019_x86
  - if %build_suite%==msvc2019_64 set SCRIPTSDIR=c:\dev\quentier-dependencies-windows\scripts\msvc2019_x64
  - set COMMONSCRIPTSDIR=c:\dev\quentier-dependencies-windows\scripts\common

install:
  - echo "Downloading ciuploadtool"
  - md c:\dev\ciuploadtool
  - cd c:\dev\ciuploadtool
  - curl -fsSL https://github.com/d1vanov/ciuploadtool/releases/download/continuous-master/ciuploadtool_windows_x86.zip -o ciuploadtool_windows_x86.zip
  - 7z x ciuploadtool_windows_x86.zip
  - if %prepare_mode%==YES c:\dev\ciuploadtool\ciuploadtool.exe -preponly
  - ps: if ($env:prepare_mode -eq "YES") { throw "Failing in order to stop the current build matrix job early" }

build_script:
  - if not exist %APPVEYOR_BUILD_FOLDER% md %APPVEYOR_BUILD_FOLDER%
# openssl
  - if exist %APPVEYOR_BUILD_FOLDER%\openssl-1_1_1u-%build_tool%_%arch_name%.zip echo "Using cached version of openssl"
  - if not exist %APPVEYOR_BUILD_FOLDER%\openssl-1_1_1u-%build_tool%_%arch_name%.zip %SCRIPTSDIR%\build_openssl.bat
# libiconv
  - if not exist %APPVEYOR_BUILD_FOLDER%\libiconv-1.15-%build_tool%_%arch_name%.zip %SCRIPTSDIR%\build_libiconv.bat else echo "Using cached version of libiconv"
# zlib
  - if not exist %APPVEYOR_BUILD_FOLDER%\zlib-1.2.11-%build_tool%_%arch_name%.zip %SCRIPTSDIR%\build_zlib.bat else echo "Using cached version of zlib"
# libxml2
  - if not exist %APPVEYOR_BUILD_FOLDER%\libxml2-2.9.7-%build_tool%_%arch_name%.zip %SCRIPTSDIR%\build_libxml2.bat else echo "Using cached version of libxml2"
# libhunspell
  - if not exist %APPVEYOR_BUILD_FOLDER%\libhunspell-1.7.0-%build_tool%_%arch_name%.zip %SCRIPTSDIR%\build_libhunspell.bat else echo "Using cached version of libhunspell"
# tidy-html5
  - if not exist %APPVEYOR_BUILD_FOLDER%\tidy-html5-5.6.0-%build_tool%_%arch_name%.zip %COMMONSCRIPTSDIR%\build_tidy_html5.bat else echo "Using cached version of tidy-html5"
# qtkeychain
  - if not exist %APPVEYOR_BUILD_FOLDER%\qtkeychain-0.9.1-%build_tool%_%arch_name%.zip %COMMONSCRIPTSDIR%\build_qtkeychain.bat else echo "Using cached version of qtkeychain"
# Google breakpad
  - if not exist %APPVEYOR_BUILD_FOLDER%\breakpad-%build_tool%_%arch_name%.zip %SCRIPTSDIR%\build_google_breakpad.bat else echo "Using cached version of google breakpad"

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - c:\dev\ciuploadtool\ciuploadtool.exe *.zip

artifacts:
  - path: '*.zip'
    name: archive

matrix:
  fast_finish: true
  allow_failures:
   - prepare_mode: YES

cache:
  - '%APPVEYOR_BUILD_FOLDER%\openssl-1_1_1u-msvc2019_x86.zip -> cache_versions\openssl-msvc2019_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\openssl-1_1_1u-msvc2019_x64.zip -> cache_versions\openssl-msvc2019_x64.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\libiconv-1.15-msvc2019_x86.zip -> cache_versions\libiconv-msvc2019_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\libiconv-1.15-msvc2019_x64.zip -> cache_versions\libiconv-msvc2019_x64.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\zlib-1.2.11-msvc2019_x86.zip -> cache_versions\zlib-msvc2019_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\zlib-1.2.11-msvc2019_x64.zip -> cache_versions\zlib-msvc2019_x64.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\libxml2-2.9.7-msvc2019_x86.zip -> cache_versions\libxml2-msvc2019_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\libxml2-2.9.7-msvc2019_x64.zip -> cache_versions\libxml2-msvc2019_x64.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\libhunspell-1.7.0-msvc2019_x86.zip -> cache_versions\libhunspell-msvc2019_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\libhunspell-1.7.0-msvc2019_x64.zip -> cache_versions\libhunspell-msvc2019_x64.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\tidy-html5-5.6.0-msvc2019_x86.zip -> cache_versions\tidy-html5-msvc2019_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\tidy-html5-5.6.0-msvc2019_x64.zip -> cache_versions\tidy-html5-msvc2019_x64.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\qtkeychain-0.9.1-msvc2019_x86.zip -> cache_versions\qtkeychain-msvc2019_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\qtkeychain-0.9.1-msvc2019_x64.zip -> cache_versions\qtkeychain-msvc2019_x64.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\breakpad-msvc2019_x86.zip -> cache_versions\breakpad-msvc2019_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\breakpad-msvc2019_x64.zip -> cache_versions\breakpad-msvc2019_x64.txt, cache_versions\global.txt'
