version: '1.0.0-{build}'

branches:
 only:
   - master

environment:
 auth_token:
   secure: rLuHhO0prerqoGCYmfOoyxqcwwamCXtuZtl4Jzqeu3aGgflk0mnX1fogLq68YcRW
 matrix:
   - prepare_mode: YES
     arch_name: none
     build_tool: none
     build_suite: none
   - prepare_mode: NO
     arch_name: x86
     build_tool: msvc
     build_suite: msvc2015
     qt: msvc2015
   - prepare_mode: NO
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
     arch_name: x64
     build_tool: msvc
     build_suite: msvc2017
     qt: msvc2017_64
   - prepare_mode: NO
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
     arch_name: x86
     build_tool: mingw
     build_suite: mingw530
     qt: mingw492_32
     HOST: i686-w64-mingw32
     platform: Win32
     configuration: Release

clone_folder: c:\dev\quentier-dependencies-windows

init:
  - if not %build_tool%==mingw set PATH=C:\Qt\5.10\%qt%\bin;%PATH%
  - if %build_tool%==mingw set PATH=C:\Qt\5.5\%qt%\bin;%PATH%
  - set ORIGPATH=%PATH%
  - if %build_suite%==msvc2017 set tool=VS2017_x64
  - if %build_suite%==msvc2015 set tool=VS2015_x86
  - if %build_suite%==mingw530 set tool=MinGW_x86
  - if %build_suite%==msvc2017 call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if %build_suite%==msvc2015 call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %platform%
  - if not %build_tool%==mingw (set MAKEFILES="NMake Makefiles") else (set MAKEFILES="MinGW Makefiles")
  - if %build_tool%==mingw set PATH=C:\MinGW\bin;C:\Program Files (x86)\CMake\bin;%PATH%
  - if %build_suite%==msvc2017 set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin;%PATH%
  - if %build_suite%==msvc2015 set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - if %build_tool%==mingw set SCRIPTSDIR=c:\dev\quentier-dependencies-windows\scripts\mingw530_x86
  - if %build_suite%==msvc2015 set SCRIPTSDIR=c:\dev\quentier-dependencies-windows\scripts\msvc2015_x86
  - if %build_suite%==msvc2017 set SCRIPTSDIR=c:\dev\quentier-dependencies-windows\scripts\msvc2017_x64
  - set COMMONSCRIPTSDIR=c:\dev\quentier-dependencies-windows\scripts\common

install:
  - echo "Downloading ciuploadtool"
  - md c:\dev\ciuploadtool
  - cd c:\dev\ciuploadtool
  - curl -fsSL https://github.com/d1vanov/ciuploadtool/releases/download/continuous-master/ciuploadtool_windows_x86.zip -o ciuploadtool_windows_x86.zip
  - 7z x ciuploadtool_windows_x86.zip
  - if %prepare_mode%==YES c:\dev\ciuploadtool\ciuploadtool.exe -preponly
  - ps: if ($env:prepare_mode -eq "YES") { throw "Failing in order to stop the current build matrix job early" }
# Get NASM (required to build OpenSSL for MinGW)
  - if %build_tool%==mingw md c:\dev\nasm
  - if %build_tool%==mingw cd c:\dev\nasm
  - if %build_tool%==mingw curl -fsSL http://libgd.blob.core.windows.net/nasm/nasm-2.07-installer.exe -o nasminst.exe
  - if %build_tool%==mingw start /wait nasminst.exe /S
  - if %build_tool%==mingw set PATH=C:\Program Files (x86)\nasm;%PATH%

build_script:
  - if not exist %APPVEYOR_BUILD_FOLDER% md %APPVEYOR_BUILD_FOLDER%
# Boost
  - if not exist %APPVEYOR_BUILD_FOLDER%\boost-1_65_0-%build_suite%_%arch_name%.zip %SCRIPTSDIR%\build_boost.bat else echo "Using cached version of boost"
# openssl
  - if not exist %APPVEYOR_BUILD_FOLDER%\openssl-1_0_2r-%build_suite%_%arch_name%.zip %SCRIPTSDIR%\build_openssl.bat else echo "Using cached version of openssl"
# libiconv
  - if not exist %APPVEYOR_BUILD_FOLDER%\libiconv-1.15-%build_suite%_%arch_name%.zip %SCRIPTSDIR%\build_libiconv.bat else echo "Using cached version of libiconv"
# zlib
  - if not exist %APPVEYOR_BUILD_FOLDER%\zlib-1.2.11-%build_suite%_%arch_name%.zip %SCRIPTSDIR%\build_zlib.bat else echo "Using cached version of zlib"
# libxml2
  - if not exist %APPVEYOR_BUILD_FOLDER%\libxml2-2.9.7-%build_suite%_%arch_name%.zip %SCRIPTSDIR%\build_libxml2.bat else echo "Using cached version of libxml2"
# libhunspell
  - if not %build_tool%==mingw set HUNSPELL_VERSION=1.7.0
  - if %build_tool%==mingw set HUNSPELL_VERSION=1.6.2
  - if not exist %APPVEYOR_BUILD_FOLDER%\libhunspell-%HUNSPELL_VERSION%-%build_suite%_%arch_name%.zip %SCRIPTSDIR%\build_libhunspell.bat else echo "Using cached version of libhunspell"
# tidy-html5
  - if not exist %APPVEYOR_BUILD_FOLDER%\tidy-html5-5.6.0-%build_suite%_%arch_name%.zip %COMMONSCRIPTSDIR%\build_tidy_html5.bat else echo "Using cached version of tidy-html5"
# qtkeychain
  - if not exist %APPVEYOR_BUILD_FOLDER%\qtkeychain-0.9.1-%build_suite%_%arch_name%.zip %COMMONSCRIPTSDIR%\build_qtkeychain.bat else echo "Using cached version of qtkeychain"
# Google breakpad
  - if not exist %APPVEYOR_BUILD_FOLDER%\breakpad-%build_suite%_%arch_name%.zip %SCRIPTSDIR%\build_google_breakpad.bat else echo "Using cached version of google breakpad"
# libbacktrace, only for MinGW
  - if %build_tool%==mingw if not exist %APPVEYOR_BUILD_FOLDER%\libbacktrace-%build_suite%_%arch_name%.zip %SCRIPTSDIR%\build_libbacktrace.bat else echo "Using cached version of libbacktrace"

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - c:\dev\ciuploadtool\ciuploadtool.exe *.zip

artifacts:
  - path: '*.zip'
    name: archive

matrix:
  fast_finish: true
  allow_failures:
   - prepare_mode: YES

cache:
  - '%APPVEYOR_BUILD_FOLDER%\boost-1_65_0-msvc2015_x86.zip -> cache_versions\boost-msvc2015_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\boost-1_65_0-msvc2017_x64.zip -> cache_versions\boost-msvc2017_x64.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\boost-1_65_0-mingw530_x86.zip -> cache_versions\boost-mingw530_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\openssl-1_0_2r-msvc2015_x86.zip -> cache_versions\openssl-msvc2015_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\openssl-1_0_2r-msvc2017_x64.zip -> cache_versions\openssl-msvc2017_x64.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\openssl-1_0_2r-mingw530_x86.zip -> cache_versions\openssl-mingw530_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\libiconv-1.15-msvc2015_x86.zip -> cache_versions\libiconv-msvc2015_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\libiconv-1.15-msvc2017_x64.zip -> cache_versions\libiconv-msvc2017_x64.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\libiconv-1.15-mingw530_x86.zip -> cache_versions\libiconv-mingw530_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\zlib-1.2.11-msvc2015_x86.zip -> cache_versions\zlib-msvc2015_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\zlib-1.2.11-msvc2017_x64.zip -> cache_versions\zlib-msvc2017_x64.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\zlib-1.2.11-mingw530_x86.zip -> cache_versions\zlib-mingw530_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\libxml2-2.9.7-msvc2015_x86.zip -> cache_versions\libxml2-msvc2015_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\libxml2-2.9.7-msvc2017_x64.zip -> cache_versions\libxml2-msvc2017_x64.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\libxml2-2.9.7-mingw530_x86.zip -> cache_versions\libxml2-mingw530_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\libhunspell-1.7.0-msvc2015_x86.zip -> cache_versions\libhunspell-msvc2015_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\libhunspell-1.7.0-msvc2017_x64.zip -> cache_versions\libhunspell-msvc2017_x64.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\libhunspell-1.6.2-mingw_x86.zip -> cache_versions\libhunspell-mingw530_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\tidy-html5-5.6.0-msvc2015_x86.zip -> cache_versions\tidy-html5-msvc2015_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\tidy-html5-5.6.0-msvc2017_x64.zip -> cache_versions\tidy-html5-msvc2017_x64.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\tidy-html5-5.6.0-mingw530_x86.zip -> cache_versions\tidy-html5-mingw530_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\qtkeychain-0.9.1-msvc2015_x86.zip -> cache_versions\qtkeychain-msvc2015_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\qtkeychain-0.9.1-msvc2017_x64.zip -> cache_versions\qtkeychain-msvc2017_x64.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\qtkeychain-0.9.1-mingw530_x86.zip -> cache_versions\qtkeychain-mingw530_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\breakpad-msvc2015_x86.zip -> cache_versions\breakpad-msvc2015_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\breakpad-msvc2017_x64.zip -> cache_versions\breakpad-msvc2017_x64.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\breakpad-mingw530_x86.zip -> cache_versions\breakpad-mingw530_x86.txt, cache_versions\global.txt'
  - '%APPVEYOR_BUILD_FOLDER%\libbacktrace-mingw530_x86.zip -> cache_versions\libbacktrace-mingw530_x86.txt, cache_versions\global.txt'
